#!/usr/bin/env bash
# Render /opt/pig/shared/.env.production from server-side secrets.
#
# Values in ~/.pig-secrets override the previous .env.production. Existing
# .env.production is loaded first as a compatibility fallback while old secrets
# are being migrated into ~/.pig-secrets. The script never prints secret values.

set -euo pipefail

SECRETS_FILE="${PIG_SECRETS_FILE:-/home/ubuntu/.pig-secrets}"
ENV_FILE="${PIG_ENV_FILE:-/opt/pig/shared/.env.production}"
ENV_INPUT_FILE="${PIG_ENV_INPUT_FILE:-$ENV_FILE}"
TMP_FILE="$(mktemp)"

load_env_file() {
  local file="$1"
  [ -f "$file" ] || return 0
  set -a
  # shellcheck disable=SC1090
  . "$file"
  set +a
}

value_of() {
  local key="$1"
  local default="${2:-}"
  printf '%s' "${!key:-$default}"
}

escape_value() {
  printf '%s' "$1" | sed \
    -e 's/\\/\\\\/g' \
    -e 's/"/\\"/g' \
    -e 's/\$/\\$/g' \
    -e 's/`/\\`/g'
}

emit() {
  local key="$1"
  local value="$2"
  printf '%s="%s"\n' "$key" "$(escape_value "$value")" >> "$TMP_FILE"
}

require_value() {
  local key="$1"
  local value="$2"
  if [ -z "$value" ]; then
    echo "Missing required production env value: $key" >&2
    exit 2
  fi
}

load_env_file "$ENV_INPUT_FILE"
load_env_file "$SECRETS_FILE"

DB_HOST_VALUE="$(value_of MYSQL_HOST "$(value_of DB_HOST 127.0.0.1)")"
DB_PORT_VALUE="$(value_of MYSQL_PORT "$(value_of DB_PORT 3306)")"
DB_USER_VALUE="$(value_of MYSQL_APP_USER "$(value_of DB_USER pig_app)")"
DB_PASS_VALUE="$(value_of MYSQL_APP_PASS "$(value_of DB_PASS)")"
DB_NAME_VALUE="$(value_of MYSQL_DATABASE "$(value_of DB_NAME pig)")"
REDIS_HOST_VALUE="$(value_of REDIS_HOST 127.0.0.1)"
REDIS_PORT_VALUE="$(value_of REDIS_PORT 6379)"
REDIS_PASS_VALUE="$(value_of REDIS_PASS)"
JWT_SECRET_VALUE="$(value_of JWT_SECRET)"

require_value DB_PASS "$DB_PASS_VALUE"
require_value JWT_SECRET "$JWT_SECRET_VALUE"

{
  echo "# PIG backend production env"
  echo "# Generated by infra/deploy/render-env-production.sh at $(date -Iseconds)"
  echo "# Do not commit this file."
  echo
} > "$TMP_FILE"

emit NODE_ENV production
emit PORT "$(value_of PORT 3000)"
echo >> "$TMP_FILE"

emit DB_HOST "$DB_HOST_VALUE"
emit DB_PORT "$DB_PORT_VALUE"
emit DB_USER "$DB_USER_VALUE"
emit DB_PASS "$DB_PASS_VALUE"
emit DB_NAME "$DB_NAME_VALUE"
emit DB_LOGGING "$(value_of DB_LOGGING false)"
emit DB_SYNCHRONIZE "$(value_of DB_SYNCHRONIZE false)"
echo >> "$TMP_FILE"

emit REDIS_HOST "$REDIS_HOST_VALUE"
emit REDIS_PORT "$REDIS_PORT_VALUE"
emit REDIS_PASS "$REDIS_PASS_VALUE"
emit REDIS_DB "$(value_of REDIS_DB 0)"
echo >> "$TMP_FILE"

emit JWT_SECRET "$JWT_SECRET_VALUE"
emit JWT_ACCESS_EXPIRES_IN "$(value_of JWT_ACCESS_EXPIRES_IN 2h)"
emit JWT_REFRESH_EXPIRES_IN "$(value_of JWT_REFRESH_EXPIRES_IN 7d)"
echo >> "$TMP_FILE"

emit ADMIN_PHONE "$(value_of ADMIN_PHONE 13800000000)"
emit ADMIN_PASSWORD "$(value_of ADMIN_PASSWORD admin123)"
echo >> "$TMP_FILE"

emit WX_MP_APPID "$(value_of WX_MP_APPID)"
emit WX_MP_SECRET "$(value_of WX_MP_SECRET)"
emit WX_OPEN_APPID "$(value_of WX_OPEN_APPID)"
emit WX_OPEN_SECRET "$(value_of WX_OPEN_SECRET)"
emit WX_PAY_MCH_ID "$(value_of WX_PAY_MCH_ID)"
emit WX_PAY_API_KEY "$(value_of WX_PAY_API_KEY)"
emit WX_PAY_NOTIFY_URL "$(value_of WX_PAY_NOTIFY_URL https://www.rockingwei.online/api/pay/wx-notify)"
echo >> "$TMP_FILE"

emit SMS_PROVIDER "$(value_of SMS_PROVIDER tencent)"
emit SMS_TENCENT_SECRET_ID "$(value_of SMS_TENCENT_SECRET_ID)"
emit SMS_TENCENT_SECRET_KEY "$(value_of SMS_TENCENT_SECRET_KEY)"
emit SMS_TENCENT_APP_ID "$(value_of SMS_TENCENT_APP_ID)"
echo >> "$TMP_FILE"

emit STORAGE_PROVIDER "$(value_of STORAGE_PROVIDER local)"
emit STORAGE_LOCAL_DIR "$(value_of STORAGE_LOCAL_DIR /opt/pig/shared/uploads)"
emit STORAGE_LOCAL_BASE_URL "$(value_of STORAGE_LOCAL_BASE_URL https://www.rockingwei.online/uploads)"
echo >> "$TMP_FILE"

emit LOG_LEVEL "$(value_of LOG_LEVEL info)"
emit LOG_PRETTY "$(value_of LOG_PRETTY false)"
emit LOG_FILE_DIR "$(value_of LOG_FILE_DIR /opt/pig/logs)"
echo >> "$TMP_FILE"

emit THROTTLE_TTL "$(value_of THROTTLE_TTL 60)"
emit THROTTLE_LIMIT "$(value_of THROTTLE_LIMIT 60)"
emit CORS_ORIGINS "$(value_of CORS_ORIGINS https://www.rockingwei.online)"
echo >> "$TMP_FILE"

emit SENTRY_DSN "$(value_of SENTRY_DSN)"
emit ALERT_WEBHOOK_URL "$(value_of ALERT_WEBHOOK_URL)"
emit DEV_LOGIN_ENABLED "$(value_of DEV_LOGIN_ENABLED false)"
echo >> "$TMP_FILE"

install -m 600 "$TMP_FILE" "$ENV_FILE"
rm -f "$TMP_FILE"

echo "Rendered $ENV_FILE from $SECRETS_FILE"
